# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: 'test'
  serviceConnection: 'rpatibandla-test-service-conn-mi'
  azureSubscriptionId: '7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a'
  loadTestResource: 'rpatibandla-test-eus'
  loadTestResourceGroup: 'rpatibandla-testruns'
  location: 'EAST US'


steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'
- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'rpatibandla-test-service-conn-spn'
    loadTestConfigFile: 'test/Sample.yaml'
    resourceGroup: 'rpatibandla-testruns'
    loadTestResource: 'rpatibandla-test-eus'
